DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));

DROP TABLE IF EXISTS STYLE;
CREATE TABLE STYLE(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));

DROP TABLE IF EXISTS LINK_AUTHOR;
CREATE TABLE LINK_AUTHOR(BOOK_ID INT, AUTHOR_ID INT);

DROP TABLE IF EXISTS LINK_STYLE;
CREATE TABLE LINK_STYLE(BOOK_ID INT, STYLE_ID INT);
